# Generated by Django 4.2 on 2023-04-16 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('product_id', models.IntegerField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=500)),
                ('product_price', models.CharField(max_length=100)),
                ('product_image', models.FileField(upload_to='images/')),
                ('product_category', models.CharField(max_length=100)),
            ],
        ),
    ]
